language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2  # Updated build-tools version
    - android-30          # Updated SDK version
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22  # Keeping this for the emulator

licenses:
  - 'android-sdk-license-.+'

before_install:
  # Accept licenses and install necessary components
  - yes | sdkmanager "platforms;android-30" "build-tools;30.0.2"
  
  # Install AVD and create emulator
  - sdkmanager "system-images;android-22;default;armeabi-v7a"
  - avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a" --force
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew assembleRelease  # Compile the app

before_deploy:
  - mkdir -p release
  - cp erxeslibrary/build/outputs/apk/release/erxeslibrary-release.apk release/

deploy:
  provider: releases
  skip_cleanup: true
  file: "release/erxeslibrary-release.apk"
  on:
    tags: true
